version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: clinic-postgres
    environment:
      POSTGRES_USER: clinic_user
      POSTGRES_PASSWORD: clinic_pass
      POSTGRES_DB: clinic_db
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
